# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0003_auto_20160512_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorie', 'verbose_name_plural': 'categorieen'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'bedrijf', 'verbose_name_plural': 'bedrijven'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'producten'},
        ),
        migrations.AddField(
            model_name='product',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 12, 18, 1, 50, 79066, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 12, 18, 1, 57, 498880, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
