# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0006_auto_20160512_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 5, 12, 18, 27, 30, 857477, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
