# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0009_auto_20160512_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
