# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricewatch', '0015_auto_20160513_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=8, max_digits=17)),
                ('paid', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricewatch.Product')),
            ],
            options={
                'verbose_name': 'advertentie',
                'verbose_name_plural': 'advertenties',
            },
        ),
    ]
