# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0016_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='reference',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
