# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0017_advertisement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='reference',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
