# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0018_auto_20160513_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='paid',
        ),
    ]
