# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0019_auto_20160513_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
