# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0020_auto_20160513_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
